apiVersion: v1
kind: Secret
metadata:
  name: invoice-postgresql
  namespace: jhipster
  labels:
    app: invoice-postgresql
type: Opaque
data:
  postgresql-password: OGI1NjRjNjJiMmU3M2JiODkzYjIwNTgxYTY4YzA1YzY4OWMxN2RhNjA4NGNhZDQ4ZDY5ODJkOWRlNzkz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-postgresql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-postgresql
  template:
    metadata:
      labels:
        app: invoice-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.1
          env:
            - name: POSTGRES_USER
              value: invoice
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoice-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-postgresql
  namespace: jhipster
spec:
  selector:
    app: invoice-postgresql
  ports:
    - port: 5432
