commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: jhipster

resources:
  - namespace.yml
  # Individual apps
  - invoice/invoice-deployment.yml
  - invoice/invoice-service.yml
  - invoice/invoice-postgresql.yml
  - notification/notification-deployment.yml
  - notification/notification-service.yml
  - notification/notification-mongodb.yml
  - store/store-deployment.yml
  - store/store-service.yml
  - store/store-postgresql.yml
  # monitoring elk
  - console/jhipster-elasticsearch.yml
  - console/jhipster-logstash.yml
  - console/jhipster-console.yml
  - console/jhipster-dashboard-console.yml
  - console/jhipster-zipkin.yml
  # service discovery eureka/consul
  - registry/jhipster-registry.yml
  - registry/application-configmap.yml

patchesJson6902:
