apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: aakil786/invoice
      context: ../invoice
      jib: {}
    - image: aakil786/notification
      context: ../notification
      jib: {}
    - image: aakil786/store
      context: ../store
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
